/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bitmap_SerialBitmap */

#ifndef _Included_bitmap_SerialBitmap
#define _Included_bitmap_SerialBitmap
#ifdef __cplusplus
extern "C" {
#endif
#undef bitmap_SerialBitmap_MAX_LEVEL
#define bitmap_SerialBitmap_MAX_LEVEL 22L
#undef bitmap_SerialBitmap_SEQUENTIAL
#define bitmap_SerialBitmap_SEQUENTIAL 1L
#undef bitmap_SerialBitmap_PARALLEL
#define bitmap_SerialBitmap_PARALLEL 2L
#undef bitmap_SerialBitmap_MAX_LEVEL
#define bitmap_SerialBitmap_MAX_LEVEL 64L
/*
 * Class:     bitmap_SerialBitmap
 * Method:    processChunk
 * Signature: ([B)[J
 */
JNIEXPORT jlongArray JNICALL Java_bitmap_SerialBitmap_processChunk
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     bitmap_SerialBitmap
 * Method:    computeStrMask
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_bitmap_SerialBitmap_computeStrMask
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
