/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bitmap_JsonSimd */

#ifndef _Included_bitmap_JsonSimd
#define _Included_bitmap_JsonSimd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bitmap_JsonSimd
 * Method:    processChunk
 * Signature: ([B)[J
 */
JNIEXPORT jlongArray JNICALL Java_bitmap_JsonSimd_processChunk
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     bitmap_JsonSimd
 * Method:    computeStrMask
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_bitmap_JsonSimd_computeStrMask
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
