/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JsonSimd */

#ifndef _Included_JsonSimd
#define _Included_JsonSimd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JsonSimd
 * Method:    processChunk
 * Signature: ([B)[J
 */
JNIEXPORT jlongArray JNICALL Java_JsonSimd_processChunk
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     JsonSimd
 * Method:    computeStrMask
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_JsonSimd_computeStrMask
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
